import Head from "next/head";
import dynamic from "next/dynamic";
import React from "react";
import { MainBackground, SuspenseLoading } from "common/components/other";
import { blogCategory } from "mock/data";

const DynamicCategoryTypeBanner = dynamic(
  () => import("modules/Category/CategoryTypeBanner"),
  { loading: () => <SuspenseLoading /> }
);
const DynamicBlogCategory = dynamic(
  () => import("modules/Category/BlogCategory"),
  {
    loading: () => <SuspenseLoading />,
  }
);
let count = 0;
let array = [];

const kq = blogCategory.reduce((blogCategories, cur) => {
  if (cur.type !== "banner" || cur.size === 12) {
    if (array.length) {
      blogCategories.push(array);
      array = [];
    }
    blogCategories.push([cur]);
  } else array.push(cur);
  return blogCategories;
}, []);

const VHNTHCM = () => {
  return (
    <div>
      <Head>
        <title>Văn hóa, nghệ thuật Hồ Chí Minh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Section Main Background */}
      <MainBackground />

      {kq.map((blogCategoryGroup, i) =>
        blogCategoryGroup[0].type === "banner" ? (
          <DynamicCategoryTypeBanner key={i} tagBanners={blogCategoryGroup} />
        ) : (
          blogCategoryGroup.map((blogCategory) => (
            <DynamicBlogCategory
              key={blogCategory._id}
              blogCategory={blogCategory}
            />
          ))
        )
      )}
    </div>
  );
};

export default VHNTHCM;
