import Head from "next/head";
import React from "react";
import { MainBackground } from "common/components/other";
import { blogCategory } from "mock/data";
import {
  CaNgoiBacHoKinhYeu,
  NhungTacPhamCuaBac,
  SanKhauKichNoi,
  VietVeBacHo,
} from "modules/Tmp/VHNTHCM";

const VHNTHCM = () => {
  return (
    <div>
      <Head>
        <title>Văn hóa, nghệ thuật Hồ Chí Minh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Section Main Background */}
      <MainBackground />

      {/* Section Những tác phẩm của Bác */}
      <NhungTacPhamCuaBac blogCategory={blogCategory[1]} />

      {/* Section Viết về Bác Hồ */}
      <VietVeBacHo blogCategory={blogCategory[0]} />

      {/* Section Sân khấu kịch nói */}
      <SanKhauKichNoi blogCategory={blogCategory[0]} />

      {/* Section Ca ngợi Bác Hồ kính yêu */}
      <CaNgoiBacHoKinhYeu blogCategory={blogCategory[2]} />
    </div>
  );
};

export default VHNTHCM;
