import React from "react";
import Head from "next/head";
import {
  main_banner_with_button,
  blogCategory,
  banner_with_button,
} from "mock/data";
import {
  Banner,
  MainBackground,
  TagBannerList,
} from "common/components/other/";
import {
  HoatDongNoiBac,
  LoiBacNamXua,
  ThanhNienLamTheoLoiBac,
} from "modules/Tmp/HTVLTLB";

const tagBanners = [
  {
    id: 1,
    title: "Văn bản chỉ đạo",
    image: "https://picsum.photos/828/436",
  },
  {
    id: 2,
    title: "Chuyên đề học tập và làm theo lời Bác",
    image: "https://picsum.photos/828/436",
  },
];
const HTVLTLB = () => {
  return (
    <>
      <Head>
        <title>Học tập và làm theo lời Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Section main background */}
      <MainBackground banner={main_banner_with_button} />

      {/* Section tag banner */}
      <TagBannerList tagBanners={tagBanners} />

      {/* Section hoạt động nổi bậc */}
      <HoatDongNoiBac blogCategory={blogCategory[0]} />

      {/* Section hoạt động nổi bậc */}
      <LoiBacNamXua blogCategory={blogCategory[0]} />

      {/* Section hoạt động nổi bậc */}
      <ThanhNienLamTheoLoiBac blogCategory={blogCategory[0]} />

      {/* Section banner */}
      <Banner banner={banner_with_button} />
    </>
  );
};

export default HTVLTLB;
