import React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { main_banner_with_button, blogCategory2 } from "mock/data";
import { MainBackground, SuspenseLoading } from "common/components/other/";

const DynamicCategoryTypeBanner = dynamic(
  () => import("modules/Category/CategoryTypeBanner"),
  { loading: () => <SuspenseLoading /> }
);
const DynamicBlogCategory = dynamic(
  () => import("modules/Category/BlogCategory"),
  {
    loading: () => <SuspenseLoading />,
  }
);
let count = 0;
let array = [];

const kq = blogCategory2.reduce((blogCategories, cur) => {
  if (cur.type !== "banner" || cur.size === 12) {
    if (array.length) {
      blogCategories.push(array);
      array = [];
    }
    blogCategories.push([cur]);
  } else array.push(cur);
  return blogCategories;
}, []);

console.log(kq);

const HTVLTLB = () => {
  return (
    <>
      <Head>
        <title>Học tập và làm theo lời Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Section main background */}
      <MainBackground banners={[main_banner_with_button]} />

      {kq.map((blogCategoryGroup, i) =>
        blogCategoryGroup[0].type === "banner" ? (
          <DynamicCategoryTypeBanner key={i} tagBanners={blogCategoryGroup} />
        ) : (
          blogCategoryGroup.map((blogCategory) => (
            <DynamicBlogCategory
              key={blogCategory._id}
              blogCategory={blogCategory}
            />
          ))
        )
      )}
    </>
  );
};

export default HTVLTLB;
