import Head from "next/head";
import dynamic from "next/dynamic";
import { MainBackground, SuspenseLoading } from "common/components/other/";

const DynamicCategoryTypeBanner = dynamic(
  () => import("modules/Category/CategoryTypeBanner"),
  { loading: () => <SuspenseLoading /> }
);
const DynamicBlogCategory = dynamic(
  () => import("modules/Category/BlogCategory"),
  {
    loading: () => <SuspenseLoading />,
  }
);

const blogCategory = [
  {
    _id: "blog_category-1",
    slug: "#",
    link: "#",
    size: 6,
    type: "banner",
    title: "Cuộc đời và hoạt động của Bác",
    button: "",
    description: "",
    image: "https://picsum.photos/828/436",
  },
  {
    _id: "blog_category-2",
    slug: "#",
    link: "#",
    size: 6,
    type: "banner",
    title: "Hình ảnh tư liệu về Bác",
    button: "",
    description: "",
    image: "https://picsum.photos/828/436",
  },
  {
    _id: "blog_category-3",
    slug: "#",
    link: "#",
    size: 6,
    type: "banner",
    title: "Những mẫu chuyện về Bác",
    button: "",
    description: "",
    image: "https://picsum.photos/828/436",
  },
  {
    _id: "blog_category-4",
    slug: "#",
    link: "#",
    size: 6,
    type: "banner",
    title: "Phim tư liệu về Bác",
    button: "",
    description: "",
    image: "https://picsum.photos/828/436",
  },
  {
    _id: "blog_category-5",
    slug: "#",
    link: "#",
    size: 12,
    type: "banner",
    title: "Địa danh lịch sử",
    button: "",
    description: "",
    image: "https://picsum.photos/828/436",
  },
];
let count = 0;
let array = [];
const kq = blogCategory.reduce((blogCategories, cur) => {
  if (cur.type !== "banner" || cur.size === 12) {
    if (array.length) {
      blogCategories.push(array);
      array = [];
    }
    blogCategories.push([cur]);
  } else array.push(cur);
  return blogCategories;
}, []);
console.log(kq);

const HTTCB = () => {
  return (
    <div>
      <Head>
        <title>Hành trình theo chân Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Section Main Background */}
      <MainBackground />

      {kq.map((blogCategoryGroup, i) =>
        blogCategoryGroup[0].type === "banner" ? (
          <DynamicCategoryTypeBanner key={i} tagBanners={blogCategoryGroup} />
        ) : (
          blogCategoryGroup.map((blogCategory) => (
            <DynamicBlogCategory
              key={blogCategory._id}
              blogCategory={blogCategory}
            />
          ))
        )
      )}
    </div>
  );
};

export default HTTCB;
