import React from "react";
import Head from "next/head";
import { DanhSachKyYeu, MainBackground } from "common/components/other";
import { main_banner_without_button } from "mock/data";

const a = [1, 2, 3, 4, 5, 6, 7];

const KyYeuThanhNienLamTheoLoiBac = () => {
  return (
    <div>
      <Head>
        <title>Thanh niên làm theo lời Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainBackground banner={main_banner_without_button} />
      <DanhSachKyYeu />
    </div>
  );
};

export default KyYeuThanhNienLamTheoLoiBac;
