import Head from "next/head";
import React from "react";
import { PaginationBar } from "common/components/control";
import { BannerDefault } from "common/components/other";
const listBooks = [
  {
    id: 1,
    title: "Sách 1",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 2,
    title: "Sách 2",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 3,
    title: "Sách 3",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 4,
    title: "Sách 4",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 5,
    title: "Sách 5",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 6,
    title: "Sách 6",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 7,
    title: "Sách 7",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 8,
    title: "Sách 8",
    image: "https://picsum.photos/300/400",
  },
  {
    id: 9,
    title: "Sách 9",
    image: "https://picsum.photos/300/400",
  },
];
const DanhSachTacPham = () => {
  return (
    <div>
      <Head>
        <title>Những tác phẩm của Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BannerDefault />
      <div className="section-wrap">
        <div className="container-fluid">
          <div className="row">
            <div className="col-11 mx-auto">
              <div className="primary-title">
                <p>3.1 Những tác phẩm của Bác</p>
              </div>
              <div className="row book-container">
                {listBooks.map((book) => (
                  <div
                    key={book.id}
                    className="col-12 col-md-6 col-lg-4 col-xxl-3"
                  >
                    <div className="book-item">
                      <div className="book-thumb">
                        <img src={book.image} alt={book.title} />
                      </div>
                    </div>
                  </div>
                ))}
                <PaginationBar />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DanhSachTacPham;
