import Head from "next/head";
import { topics, diaries } from "mock/data";
import { MainBackground } from "common/components/other/";
import { Topics, Introduction, HotNews, Diaries } from "modules/Home";
import { Checkbox } from "@mui/material";

export default function Home() {
  const label = { inputProps: { "aria-label": "Checkbox demo" } };
  return (
    <div>
      <Head>
        <title>Thanh niên làm theo lời Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/assets/fonts/font-awesome.css"
          as="style"
          type="text/css"
          crossOrigin="anonymous"
        />
      </Head>
      {/* Section Main Background */}
      <MainBackground />

      {/* Section Topics */}
      <Topics topics={topics} />

      {/* Section Introduction */}
      <Introduction />

      {/* Section Hot News */}
      <HotNews />

      {/* Section Diaries */}
      <Diaries diaries={diaries} />
    </div>
  );
}
