import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { MainBackground } from "common/components/other/";
import { getAll, getTop } from "utils/axios";
import { SuspenseLoading } from "common/components/other";
import { topics, diaries } from "mock/data";
import axios from "axios";

const DynamicTopics = dynamic(() => import("modules/Home/Topics"), {
  loading: () => <SuspenseLoading />,
});
const DynamicIntroduction = dynamic(() => import("modules/Home/Introduction"), {
  loading: () => <SuspenseLoading />,
});
const DynamicHotNews = dynamic(() => import("modules/Home/HotNews"), {
  loading: () => <SuspenseLoading />,
});
const DynamicDiaries = dynamic(() => import("modules/Home/Diaries"), {
  loading: () => <SuspenseLoading />,
});

export async function getServerSideProps() {
  const resTopics = await getAll("topics");
  const dataTopics = resTopics?.data?.data || null;

  const pinnedBlogs = await getTop("blogs");
  const dataPinBlogs = pinnedBlogs?.data?.data || null;

  const resDiaries = await getAll("diaries");
  const dataDiaries = resDiaries?.data?.data || null;

  return { props: { dataTopics, dataPinBlogs, dataDiaries } };
}

export default function Home({ dataTopics, dataPinBlogs, dataDiaries }) {
  return (
    <div>
      <Head>
        <title>Thanh niên làm theo lời Bác</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/assets/fonts/font-awesome.css"
          as="style"
          type="text/css"
          crossOrigin="anonymous"
        />
      </Head>

      {/* Section Main Background */}
      <MainBackground />

      {/* Section Topics */}
      <DynamicTopics />

      {/* Section Introduction */}
      <DynamicIntroduction />

      {/* Section Hot News */}
      <DynamicHotNews pinnedBlogs={dataPinBlogs} />

      {/* Section Diaries */}
      <DynamicDiaries diaries={dataDiaries} />
    </div>
  );
}
