export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_TOPICS = "GET_TOPICS";

export const GET_ACHIEVEMENT_FIELDS = "GET_ACHIEVEMENT_FIELDS";
export const CREATE_ACHIEVEMENT_FIELDS = "CREATE_ACHIEVEMENT_FIELDS";
export const UPDATE_ACHIEVEMENT_FIELDS = "UPDATE_ACHIEVEMENT_FIELDS";

export const CREATE_ACHIEVEMENT = "CREATE_ACHIEVEMENT";
export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT";
